### PR TITLE
Fix building wheels with py.typed files

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by srittau** [comment]
Currently, the integration tests fail, since py.typed is not recognized. I'm not sure, why the tests didn't flag this in #109. Cc @Avasam

**Comment by srittau** [comment]
I think the tests fail locally, because previous runs create py.typed, which subsequent runs then pick up. I'll investigate more.

**Comment by Avasam** [comment]
I think we check for file extensions to only accept `.pyi` and `.md` found in typeshed.
But after running once, a `py.typed` is added, which is then seen on a second run because the run is not cleaned up locally (on CI it doesn't matter since it's a temporary clone of typeshed iirc)

I see two potential solutions:
1. We could allow `py.typed` in our check. But that will allow `py.typed` files to slip in typeshed's source. We may not want that?
2. Add clean-up code.

**Comment by srittau** [comment]
The main problem here is that the integration tests modify files outside the stub uploader directory and don't clean up. I'll open a separate issue.

**Pull request closed without merging**
