### PR TITLE
Mention pyright in the stubs' README

### PR DESCRIPTION
**Pull request by Avasam**
Same suggestion as https://github.com/python/typeshed/pull/9472

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
Maybe add [`pyre`](https://github.com/facebook/pyre-check) to this list as well? `pyre` has 6.2k stars on GitHub compared to e.g. 4k stars for `pytype` :)

**Review by srittau — APPROVED** [review]

**Comment by Avasam** [comment]
> Maybe add [`pyre`](https://github.com/facebook/pyre-check) to this list as well? `pyre` has 6.2k stars on GitHub compared to e.g. 4k stars for `pytype` :)

Sure can, I just didn't remember about pyre since typeshed doesn't text directly against it.

**Comment by srittau** [comment]
I think we should skip pyre for now, since the stubs are not tested against it.

**Comment by AlexWaygood** [comment]
> I think we should skip pyre for now, since the stubs are not tested against it.

No strong opinion! This PR is a clear improvement as-is; don't want to block it

**Pull request merged**
